name: sire_frontend
description: SIRE Frontend

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  adaptive_breakpoints: ^0.0.4
  animations: ^2.0.0
  collection: ^1.15.0
  cupertino_icons: ^1.0.2
  flutter_gallery_assets: ^1.0.2
  flutter_localized_locales: ^2.0.1
  flutter_staggered_grid_view: ^0.4.0
  google_fonts: ^2.0.0
  intl: ^0.17.0
  meta: ^1.3.0
  package_info: ^2.0.0
  provider: ^5.0.0
  rally_assets: ^3.0.1
  scoped_model: ^2.0.0-nullsafety.0
  shrine_images: ^2.0.1
  url_launcher: ^6.0.3
  vector_math: ^2.1.0
  #flutter_gallery: ^2.4.0+20400

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  camera:
  path_provider:
  path:
  currency_text_input_formatter: ^2.0.0
  datetime_picker_formfield: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  args: ^2.0.0
  grinder: ^0.9.0
  path: ^1.8.0
  pedantic: ^1.11.0
  string_scanner: ^1.1.0
  test: ^1.16.8
  web_benchmarks: ^0.0.5
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: 'images/Sire_Pagos.png'
  android: true
  ios: true

dependency_overrides:
  path_provider: ^2.0.0-nullsafety.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
    - packages/flutter_gallery_assets/assets/studies/rally_card_dark.png
    - packages/flutter_gallery_assets/assets/studies/rally_card.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo.png
    - packages/flutter_gallery_assets/assets/logo/flutter_logo_color.png
    - packages/flutter_gallery_assets/assets/icons/cupertino/cupertino.png
    - packages/flutter_gallery_assets/assets/icons/material/material.png
    - packages/flutter_gallery_assets/assets/icons/reference/reference.png
    - packages/flutter_gallery_assets/assets/demos/bottom_navigation_background.png
    - packages/flutter_gallery_assets/fonts/GalleryIcons.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-Light.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoMono-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-ExtraBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Oswald-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Merriweather-BoldItalic.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Raleway-Light.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/RobotoCondensed-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/LibreFranklin-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Montserrat-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Rubik-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/Eczar-SemiBold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Regular.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Medium.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Bold.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-Thin.ttf
    - packages/flutter_gallery_assets/fonts/google_fonts/WorkSans-SemiBold.ttf
    - packages/flutter_gallery_assets/placeholders/avatar_logo.png
    - packages/flutter_gallery_assets/placeholders/placeholder_image.png
    - packages/flutter_gallery_assets/splash_effects/splash_effect_1.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_2.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_3.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_4.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_5.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_6.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_7.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_8.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_9.gif
    - packages/flutter_gallery_assets/splash_effects/splash_effect_10.gif
    - packages/rally_assets/logo.png
    - packages/rally_assets/thumb.png
    - images/Sire_Pagos.png
    - images/rally_card.png

  generate: true
  uses-material-design: true
  fonts:
    - family: GalleryIcons
      fonts:
        - asset: packages/flutter_gallery_assets/fonts/GalleryIcons.ttf

